# fly.toml app configuration file generated for react-tech-blog on 2023-07-31T11:30:33-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-tech-blog"
primary_region = "iad"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
